<?php

declare(strict_types=1);
require_once __DIR__ . '/hospital_context.php';

function report_h(string $v): string { return htmlspecialchars($v, ENT_QUOTES, 'UTF-8'); }

$total_patients=0;
$st=mysqli_prepare($conn,"SELECT COUNT(*) FROM patient_hospital_mapping WHERE hospital_id=?"); mysqli_stmt_bind_param($st,'i',$hospital_id); mysqli_stmt_execute($st); mysqli_stmt_bind_result($st,$total_patients); mysqli_stmt_fetch($st); mysqli_stmt_close($st);

$total_appointments=0; $st=mysqli_prepare($hospital_conn,"SELECT COUNT(*) FROM appointments WHERE YEAR(appointment_date)=YEAR(CURDATE()) AND MONTH(appointment_date)=MONTH(CURDATE())"); mysqli_stmt_execute($st); mysqli_stmt_bind_result($st,$total_appointments); mysqli_stmt_fetch($st); mysqli_stmt_close($st);
$total_doctors=0; $r=mysqli_query($hospital_conn,"SELECT COUNT(*) FROM doctors WHERE status='Active'"); if($r){$total_doctors=(int)mysqli_fetch_row($r)[0];mysqli_free_result($r);}
$total_revenue=0; $r=mysqli_query($hospital_conn,"SELECT COALESCE(SUM(amount),0) FROM payments WHERE payment_status='Success' AND YEAR(paid_at)=YEAR(CURDATE()) AND MONTH(paid_at)=MONTH(CURDATE())"); if($r){$total_revenue=(float)mysqli_fetch_row($r)[0];mysqli_free_result($r);}

$rev_labels=[];$rev_data=[];$dt=new DateTime('first day of this month');$dt->modify('-5 months');for($i=0;$i<6;$i++){ $rev_labels[]=$dt->format('M'); $st=mysqli_prepare($hospital_conn,"SELECT COALESCE(SUM(amount),0) FROM payments WHERE payment_status='Success' AND YEAR(paid_at)=? AND MONTH(paid_at)=?");$y=(int)$dt->format('Y');$m=(int)$dt->format('m');mysqli_stmt_bind_param($st,'ii',$y,$m);mysqli_stmt_execute($st);mysqli_stmt_bind_result($st,$v);mysqli_stmt_fetch($st);mysqli_stmt_close($st);$rev_data[]=round((float)$v,2);$dt->modify('+1 month');}

$dept_labels=[];$dept_data=[];$q="SELECT d.department_name,COUNT(DISTINCT a.mapping_id) total FROM departments d LEFT JOIN doctors doc ON doc.department_id=d.department_id LEFT JOIN appointments a ON a.doctor_id=doc.doctor_id GROUP BY d.department_id ORDER BY total DESC,d.department_name LIMIT 8";$r=mysqli_query($hospital_conn,$q);if($r){while($x=mysqli_fetch_assoc($r)){ $dept_labels[]=$x['department_name'];$dept_data[]=(int)$x['total'];}mysqli_free_result($r);}
if(!$dept_labels){$dept_labels=['No Data'];$dept_data=[0];}

$appt_labels=[];$appt_data=[];$r=mysqli_query($hospital_conn,"SELECT DATE_FORMAT(appointment_date,'%b') label,COUNT(*) total,MIN(appointment_date) sort_date FROM appointments WHERE appointment_date>=DATE_FORMAT(DATE_SUB(CURDATE(),INTERVAL 5 MONTH),'%Y-%m-01') GROUP BY YEAR(appointment_date),MONTH(appointment_date),label ORDER BY sort_date");if($r){while($x=mysqli_fetch_assoc($r)){ $appt_labels[]=$x['label'];$appt_data[]=(int)$x['total'];}mysqli_free_result($r);}
if(!$appt_labels){$appt_labels=['No Data'];$appt_data=[0];}

$summary=[];$q="SELECT d.department_name,COALESCE(SUM(p.amount),0) revenue FROM departments d LEFT JOIN doctors doc ON doc.department_id=d.department_id LEFT JOIN appointments a ON a.doctor_id=doc.doctor_id LEFT JOIN billing b ON b.appointment_id=a.appointment_id LEFT JOIN payments p ON p.bill_id=b.bill_id AND p.payment_status='Success' GROUP BY d.department_id ORDER BY revenue DESC LIMIT 8";$r=mysqli_query($hospital_conn,$q);if($r){while($x=mysqli_fetch_assoc($r))$summary[]=$x;mysqli_free_result($r);}

$report_date=date('d M Y');
$report_rows=[['Revenue Report','Finance','Monthly Financial Report'],['Patients Report','Patients','Registered Patients'],['Appointments Report','Appointments','Appointment Summary'],['Doctors Report','Doctors','Active Doctors']];
$chart_data=['revenueLabels'=>$rev_labels,'revenueData'=>$rev_data,'departmentLabels'=>$dept_labels,'departmentData'=>$dept_data,'appointmentLabels'=>$appt_labels,'appointmentData'=>$appt_data];
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Reports Dashboard</title><link rel="stylesheet" href="sidebar.css"><link rel="stylesheet" href="reports.css"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"><script src="https://cdn.jsdelivr.net/npm/chart.js"></script></head><body><div class="dashboard"><?php require 'sidebar.php';?><main class="main-content">
<div class="page-header"><div><h1>Reports</h1><p>Generate and analyze hospital reports.</p></div><div class="header-buttons"><button class="pdf-btn" id="exportPdf"><i class="fa-solid fa-file-pdf"></i> Export PDF</button><button class="excel-btn" id="exportExcel"><i class="fa-solid fa-file-excel"></i> Export Excel</button></div></div>
<div class="stats-container"><div class="stat-card"><div class="stat-icon revenue"><i class="fa-solid fa-indian-rupee-sign"></i></div><div class="stat-info"><h4>Total Revenue</h4><h2>₹ <?=number_format($total_revenue,2)?></h2><p>This Month</p></div></div><div class="stat-card"><div class="stat-icon patients"><i class="fa-solid fa-bed-pulse"></i></div><div class="stat-info"><h4>Total Patients</h4><h2><?=number_format($total_patients)?></h2><p>Registered Patients</p></div></div><div class="stat-card"><div class="stat-icon appointments"><i class="fa-solid fa-calendar-check"></i></div><div class="stat-info"><h4>Total Appointments</h4><h2><?=number_format($total_appointments)?></h2><p>This Month</p></div></div><div class="stat-card"><div class="stat-icon doctors"><i class="fa-solid fa-user-doctor"></i></div><div class="stat-info"><h4>Total Doctors</h4><h2><?=number_format($total_doctors)?></h2><p>Active Doctors</p></div></div></div>
<div class="charts-section"><div class="chart-card revenue-chart"><div class="card-header"><h3>Revenue Overview</h3><i class="fa-solid fa-ellipsis"></i></div><div class="chart-box"><canvas id="revenueChart"></canvas></div></div><div class="chart-card department-chart"><div class="card-header"><h3>Patients by Department</h3><i class="fa-solid fa-ellipsis"></i></div><div class="donut-container"><canvas id="departmentChart"></canvas></div></div><div class="chart-card appointment-chart"><div class="card-header"><h3>Monthly Appointments</h3><i class="fa-solid fa-ellipsis"></i></div><div class="chart-box"><canvas id="appointmentChart"></canvas></div></div><div class="chart-card summary-card"><div class="card-header"><h3>Revenue Summary</h3><i class="fa-solid fa-ellipsis"></i></div><div class="summary-list"><?php if($summary): foreach($summary as $x):?><div class="summary-item"><span><?=report_h((string)$x['department_name'])?></span><strong>₹<?=number_format((float)$x['revenue'],2)?></strong></div><?php endforeach; else:?><div class="summary-item"><span>No revenue data</span><strong>₹0.00</strong></div><?php endif;?></div></div></div>
<div class="table-container"><table id="reportsTable"><thead><tr><th>Report Name</th><th>Category</th><th>Generated On</th><th>Status</th><th>Download</th></tr></thead><tbody><?php foreach($report_rows as $i=>$rr):?><tr><td><div class="report-info"><div class="report-icon"><i class="fa-solid <?=['fa-file-lines','fa-user-injured','fa-calendar-check','fa-user-doctor'][$i]?>"></i></div><div><h4><?=report_h($rr[0])?></h4><span><?=report_h($rr[2])?></span></div></div></td><td><?=report_h($rr[1])?></td><td><?=report_h($report_date)?></td><td><span class="status ready">Ready</span></td><td><button class="download-btn report-download" data-report="<?=report_h($rr[0])?>"><i class="fa-solid fa-download"></i> Download</button></td></tr><?php endforeach;?></tbody></table></div>
</main></div><script>window.reportChartData=<?=json_encode($chart_data,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>;</script><script src="reports.js"></script></body></html>
